### ISSUE TITLE
Unclear how to get payload from the validator.check call

### ISSUE THREAD

**Issue by jgubman** [google/google-id-token#13]
Apologies if I'm using the APIs incorrectly, I can't find a clear guide to getting the authenticated user's email when supplied with their 'code' via the Identity Platform Javascript API's #grantOfflineAccess function (described here: https://developers.google.com/identity/sign-in/web/server-side-flow)

Once I've gotten that 'code' from the client, I send it to my server and use:

```
      secrets = Google::APIClient::ClientSecrets.load "config/gplus.json"`
      auth = secrets.to_authorization
      auth.code = params[:auth]
      auth.fetch_access_token!
      
      validator = GoogleIDToken::Validator.new(expiry: 1800)
      payload = validator.check(auth.id_token, secrets.client_id) `
```
but payload is nil. If I inspect the validator object, I can see the email I'm looking for and can access it with the following kludge:
   `validator.instance_variable_get('@tokens').first`

But that seems wrong and brittle.

**Comment by jgubman** [comment]
Figured out the problem, lines 112 and 113 make it impossible to verify the token if you don't pass in the app's client ID twice on the #check signature as both the aud and client_id:
`validator.check(auth.id_token, secrets.client_id, secrets.client_id)`

Confusing because 1) the gem accepts nil as a client_id and 2) the google documentation only references an `aud` in the token:
https://developers.google.com/identity/sign-in/web/backend-auth

**Comment by mrstif** [comment]
@jgubman your issue is that you're using the old gem version and not the master one which hasn't yet received a release version.

The documentation you should be using for that version is described here: https://github.com/google/google-id-token/blob/5110c74e5943eb7a685a2b771fc8d062a0a2c412/README.rdoc

If you want to use the new code you'll have to track the master branch.

**Comment by dazuma** [comment]
This project is deprecated, and we're archiving the repository. The functionality is available in the `googleauth` gem. See https://github.com/googleapis/google-auth-library-ruby.
