### ISSUE TITLE
version bump

### ISSUE THREAD

**Issue by eugenejen** [google/google-id-token#15]
It seems like the master is in 1.3.1 in https://rubygems.org/gems/google-id-token/versions/1.3.1 is different from master. which is also label as 1.3.1.

We should bump the version of master to 1.3.2 and release it. Due to addition of classes for exceptions. GoogleIDToken::ValidationError is an undefined symbol.

**Comment by AlexVPopov** [comment]
Yes, I discovered this as well. My solution is to use the gem by specifying the GitHub repo as the source for it in the Gemfile.

**Comment by eugenejen** [comment]
My team feel annoying to use Github repo directly due to jenkins ssh key known host issue during build time. I in the end has to use rubygem use the 2015 version. I suggest if master is working. we should bump version and push it to rubygem.

**Comment by logitron** [comment]
+1 - It would be nice to have the recent updates without having to point to the GitHub repo for source.  Any status on when this might get done?

**Comment by eugenejen** [comment]
Since no one is doing. I push a one character PR hoping that won't break anything (surprisingly, no test suite rake task there. anyone wants to add it?)

**Comment by morgoth** [comment]
Is there any chance to have a stable release?

**Comment by hxiong388** [comment]
[Version 1.4.0](https://rubygems.org/gems/google-id-token) has been released.
