### ISSUE TITLE
validator.check is always returning nil

### ISSUE THREAD

**Issue by yedhukrishnan** [google/google-id-token#21]
I am trying to parse the JWT ID token from my client ID. I parsed the token and got my `required_audience` and it is same as `required_client_id`. But,

``` ruby
payload = validator.check(token, required_audience, required_client_id)
```

This is always returning me `nil`. Any idea why?

I generated the token on Android using the following code:

``` java
// Configure Google Sign-In with the requestIdToken
GoogleSignInOptions googleSignInOptions = new GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
                .requestIdToken(getString(R.string.server_client_id))
                .requestEmail()
                .build();

// Handle result
private void handleSignInResult(GoogleSignInResult result) {
    if (result.isSuccess()) {
        GoogleSignInAccount account = result.getSignInAccount();
        String tokenId = account.getIdToken();
    }
}
```

The token is indeed generated by Google. But, in Ruby, I get this error:

``` ruby 
irb> validator.problem
 => "Token not verified as issued by Google"
```

**Comment by hxiong388** [comment]
@yedhukrishnan The new v1.4.0 gem worked for me on a token I got from JS sign-in. Please give it a shot see if the issue is resolved.

**Comment by dazuma** [comment]
This project is deprecated, and we're archiving the repository. The functionality is available in the `googleauth` gem. See https://github.com/googleapis/google-auth-library-ruby.
