### ISSUE TITLE
Need ability to specify public certs URL for ID Token verification

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/google-id-token#3]
```
See:
https://code.google.com/p/google-id-token/source/browse/lib/google-id-token.rb#3
3

Need an ability to customize that URL.

```

Original issue reported on code.google.com by `yan...@google.com` on 24 Mar 2013 at 11:26

**Comment by dazuma** [comment]
This project is deprecated, and we're archiving the repository. The functionality is available in the `googleauth` gem. See https://github.com/googleapis/google-auth-library-ruby.
