### ISSUE TITLE
Is this production ready?

### ISSUE THREAD

**Issue by joshkurz** [google/google-id-token#31]
I see in the comments here https://github.com/google/google-api-ruby-client/blob/master/samples/web/app.rb#L69 that this lib is not production ready? Is this true?

What is the suggested method of checking ID tokens if, this is not the supported lib?

Thanks

**Comment by mrstif** [comment]
Hi @joshkurz 

Can't talk for the guys at Google but I've been using it at my company successfully for a while now.
Pretty sure the comment in that file is out of date since this gem itself changed a lot since then.

Hope it helps

**Comment by joshkurz** [comment]
Thank you @mrstif that does help. We have deployed it as well for almost a month now. Is running very well also.
