### ISSUE TITLE
uninitialized constant JWT::ExpiredSignature

### ISSUE THREAD

**Issue by yamchi** [google/google-id-token#33]
hello ! just followed this in stackoverflow  [https://stackoverflow.com/questions/45262755/how-to-validate-google-token-id-sent-from-android-on-ruby-on-rails-server](url)

`validator = GoogleIDToken::Validator.new(expiry: 1800)
begin
  payload = validator.check(token, required_audience, required_client_id)
  email = payload['email']
rescue GoogleIDToken::ValidationError => e
  report "Cannot validate: #{e}"
end`

but i'm getting an error uninitialized constant JWT::ExpiredSignature

**Comment by mahemoff** [comment]
Your stackoverflow link is broken Here:. https://stackoverflow.com/questions/45262755/how-to-validate-google-token-id-sent-from-android-on-ruby-on-rails-server

**Comment by dazuma** [comment]
This project is deprecated, and we're archiving the repository. The functionality is available in the `googleauth` gem. See https://github.com/googleapis/google-auth-library-ruby.
