### ISSUE TITLE
Multiple client ids

### ISSUE THREAD

**Issue by jesster2k10** [google/google-id-token#37]
How can you provide multiple client ids as per the google docs example here (note this is javascript code) https://developers.google.com/identity/sign-in/ios/backend-auth

```js
const ticket = await client.verifyIdToken({
      idToken: token,
      audience: CLIENT_ID,  // Specify the CLIENT_ID of the app that accesses the backend
      // Or, if multiple clients access the backend:
      //[CLIENT_ID_1, CLIENT_ID_2, CLIENT_ID_3]
  });
```

I tried passing in an array as the second parameter when calling `validator.check` but that seems to not work.

When I pass just a single string, the code works fine. Else I get an error like so:

`GoogleIDToken::AudienceMismatchError: Token audience mismatch`

**Comment by jesster2k10** [comment]
Just figured out there was a pull request merged for this issue https://github.com/google/google-id-token/pull/30

So I'll close this one

**Comment by cassiompf** [comment]
For some reason this doesn't work for me either, I'm using ruby in version 3.0.2 and I'm trying to do something like:

```
#
# I took the part of the demo code that I use in business_process
#
CLIENTS_ID = {
  ios: Rails.application.credentials[Rails.env.to_sym].dig(:google_auth, :ios_client_id),
  android: Rails.application.credentials[Rails.env.to_sym].dig(:google_auth, :android_client_id),
  web: Rails.application.credentials[Rails.env.to_sym].dig(:google_auth, :web_client_id)
}.freeze

@validator = GoogleIDToken::Validator.new

def validate_token
  @response = @validator.check(oauth2_params[:oauth2_token], @clients_authorized)
rescue GoogleIDToken::ValidationError => error
  puts error
end

validate_token()
```

This is returning an error with the message: 'Token audience mismatch'. 

I tried to look at the code of the project where it does this verification and found that on line 135 of the [token verification file](https://github.com/google/google-id-token/blob/master/lib/google-id-token.rb) it does this verification: `if !(payload.has_key?('aud') && Array(aud).include?(payload['aud']))`, but I don't know why it doesn't work
