### ISSUE TITLE
Version bump (redo #15)

### ISSUE THREAD

**Issue by ariccio** [google/google-id-token#38]
It seems like google has forgotten to release updates for this gem. This is the same problem as #15 , but again. Can someone at google bump this?

After scouring the docs, there doesn't seem to be ANY other officially recommended way to validate tokens *from* the frontend on a ruby backend.  I've been scratching my head for several hours here. There's no link in the docs to any kind of entry in the modern ruby gapi clients.

**Comment by dazuma** [comment]
This gem has been superseded by a class in the googleauth gem. See https://googleapis.dev/ruby/googleauth/latest/Google/Auth/IDTokens.html

We do need to update the readme on this gem to point everyone there.

**Comment by ariccio** [comment]
Thank you for responding so quickly, before I even had a chance to commit my changes to the code that I'm working on 🤣.


That's good to hear, and that new api does look much better. It's not just the readme that needs updating though, the docs for the login flow itself need some clarification: 
![Screenshot_20210317-194351](https://user-images.githubusercontent.com/2142308/111552916-b4cb6600-8759-11eb-8e74-82fcf5993ca1.png)
...they don't link to a google implementation for verifying tokens! Perhaps that's why some widely used gems like `google_sign_in` still use this old gem.

**Comment by Bismarck-GM** [comment]
Can we say this gem is 'dead' but still working?

Really I couldn't find anything in Google pointing me in the right direction besides this issue.

**Comment by ariccio** [comment]
I ended up not using it. It might be a good idea to add a depreciation warning to the gem somewhere hard for developers to miss?

**Comment by ariccio** [comment]
(I've been using `googleauth` for a year now in prod, it works well!)

**Comment by dazuma** [comment]
This project is deprecated, and we're archiving the repository. The functionality is available in the `googleauth` gem. See https://github.com/googleapis/google-auth-library-ruby. I've replaced the README with a notice to go look at googleauth.
